From: "=?koi8-r?B?6dfBziD108vP1w==?=" <ivus@geocities.com>
To: "Ivan Uskov" <p3.f101.n5055.z2.fidonet.org>
Subject: =?koi8-r?B?79TXxdQ6IHRlc3Q=?=
Date: Sun, 1 Aug 1999 09:53:35 +0400
Message-ID: <01bedbe2$31fd5390$0100a8c0@ivus>
MIME-Version: 1.0
Content-Type: text/plain;
    charset="koi8-r"
Content-Transfer-Encoding: 8bit
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 4.71.1712.3
X-MimeOLE: Produced By Microsoft MimeOLE V4.71.1712.3


-----Исходное сообщение-----
От: Ivan Uskov <p3.f101.n5055.z2.fidonet.org>
Группы: vg.test
Дата: 21 июля 1999 г. 1:46
Тема: test


>TEST
>
>--
>       \Ivan
>
>--- InterSquish NNTP Server/FTN Gate V.1.2.0
> * Origin: ... Default InterSquish Origin ... (2:5055/101.3)
>

.
